### ISSUE TITLE
Where is the Transfer Speed information?!

### ISSUE THREAD

**Issue by ypy-pasha** [resurrecting-open-source-projects/dcfldd#23]
This Called Enhanced version of DD, but DD have speed info and this DCFLDD no have!
Whats reason for remove this default feature from orginal DD Tool?

**Comment by davidpolverari** [comment]
Had you given more the a cursory look at the [README.md file](https://github.com/resurrecting-open-source-projects/dcfldd/blob/master/README.md), you would realize that:

- "we" (the current dclfdd maintainers) are striving to keep the project alive long after the original work on it by the original authors ceased. We just happen to use the same description for the project ("enhanced version of GNU dd") the same way the original author did[^orig_page]. 
- dcfldd was initially forked from GNU dd circa 2002. By that time, dcfldd implemented many features missing in dcfldd, making it at the time a really "enhanced version of dd". Some of those, like `status=progress` (which I infer is the one you're complaining about), only were implemented in GNU dd by 2015[^coreutils_release], albeit the latter implemented the speed information in addition to block and record statistics. So no, we didn't "remove this default feature from original dd".
- As of today, dcfldd still has features that GNU dd doesn't have, like hashing support. That still makes it "an enhanced version of dd".

Happy New Year!

[^orig_page]: https://dcfldd.sourceforge.net/
[^coreutils_release]: https://savannah.gnu.org/forum/forum.php?forum_id=8309

**Comment by davidpolverari** [comment]
Closing, as this was more of a question than an issue, and it was answered above.

**Comment by PeterSuh-Q3** [comment]
As you said, dd after 2015 supports the status=progress option, and the current dcfldd displays the created blocks and capacity well regardless of this option.

But I would like to use one more option. bs=8M.
If I use this option, transfer progress will not be displayed.
The same applies if I use status=progress together.

Can you solve this problem?

**Comment by davidpolverari** [comment]
I just tested using `bs=8M` and the block transfer progress is shown as well. Sometimes due to the speed of your hardware and to the size of the input file, you will not see the progress because the copy will be fast. That happened to me with a 3.0G file.

To ensure it works, try copying more blocks from a larger input file, eg:

```bash
dcfldd if=/dev/zero of=output bs=8M count=2048
```

Please let me know if it is a different problem.

**Comment by PeterSuh-Q3** [comment]
I'm sorry. I didn't mention my OS environment.
I am running it in the terminal app of MacOS Ventura 13.4.1.

The IMG file used is approximately 1.5G.
https://github.com/PeterSuh-Q3/tinycore-redpill/releases/download/v1.0.1.0/tinycore-redpill.v1.0.1.0.m-shell.img.gz

I tried using the options you mentioned, but the block transfer progress is not displayed.

Instead of /dev/disk#, I used /dev/rdisk# for faster access, but the results were the same in both attempts.

Finally, I also tried the options you used.
Only in this case will the output be normal.

thank you


![스크린샷 2024-02-11 오후 10 48 14](https://github.com/resurrecting-open-source-projects/dcfldd/assets/85427533/4c47631b-33dc-43ba-983d-454237711bbf)

I tried varying the values of the bs option without count.
The problem occurs only at 8M.

![스크린샷 2024-02-11 오후 10 51 24](https://github.com/resurrecting-open-source-projects/dcfldd/assets/85427533/c3cd4378-0bb0-4fc3-8ee9-6022ed8da2d2)

**Comment by PeterSuh-Q3** [comment]
For now, the best compromise is around bs=512k.
Changes are in increments of "256 blocks (128Mb)".

![스크린샷 2024-02-11 오후 11 20 43](https://github.com/resurrecting-open-source-projects/dcfldd/assets/85427533/20621a7b-242d-46d4-a019-16a26d2899cd)

**Comment by davidpolverari** [comment]
I will have a look at it when I have time.
